config/routes.rb
Rails.application.routes.draw do

  root 'raz#index'
  get 'index', to: 'raz#index'
  get 'bio', to: 'raz#bio'
  get 'links', to: 'raz#links'
  get 'projects', to: 'raz#projects'
  get 'posts', to: 'raz#posts'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/raz_controller.rb
class RazController < ApplicationController
    def index
    end
    def bio
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raƶgriƶ One</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.5.0/octicons.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-sanitize.min.js"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/raz/bio.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="imgref/razIcon.png">
    <!--CSS stylesheets -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/raz.css">
    <link rel="stylesheet" href="css/animate.css">
    <!-- Js scripts -->
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
     <script src="js/bootstrap.min.js"></script>
     <script src="js/npm.js"></script>
     <script src="js/razgriz.js"></script>
</head>
<body>

<header>
    <div class="container-fluid spaced text-center animated fadeInDown" id="header">
        <div class="w3-center w3-container" id="Title">
            <div class="w3-hide-small">
                <a href="index.html"><img src="imgref/RazLogo.png" alt="Logo" style="width: 35%; height: 35%; margin-top: -140px; margin-bottom: -100px;"></a>
            </div>
            <div class="w3-hide-medium w3-hide-large">
                <a href="index.html"><img src="imgref/RazLogo.png" alt="logo" style="width: 60%; height: 60%; margin-top: -140px; margin-bottom: -100px;"></a>
            </div>
        </div>
        <div>
            <em>Pedro Pereira, IME - USP</em>
        </div>
    </div>
    <ul class="w3-navbar w3-border w3-black w3-card-4 animated fadeInDown" style="border: 0px !important;" id="InitNavbar">
        <li><a class="w3-red w3-hover-white" href="#"><b>Bio</b></a></li>
        <li><a class="w3-hover-red" href="links.html"><b>Links</b></a></li>
        <li><a class="w3-hover-red" href="posts.html"><b>Posts</b></a></li>
        <li><a class="w3-hover-red" href="projects.html"><b>Projects</b></a></li>
    </ul>
</header>

<div class="animated fadeInUp" style="padding: 20px; background-color: #EE1000; color: #000">
    <h1 class="w3-center"><b>Pedro Leyton Pereira</b></h1>
</div>
<br>
<div class="w3-quarter animated fadeInUp">
    <div class="wrapper-center">
        <a onclick="spinImg('me')"><img src="imgref/me.jpg" class="img-circle" id="me"></a>
    </div>
</div>
<div class="w3-rest w3-container animated fadeInUp">
    <div class="bio-segment">
        <h3 class="w3-center"><b>Student of Computer Science at the Institute of Maths and Statistics, University of S&atilde;o Paulo</b></h3>
        <p>&emsp;&emsp;&emsp;&emsp;
            Entrou na USP com 17 anos, em 2016. Fan&aacute;tico por computa&ccedil;&atilde;o, especialmente quando o assunto &eacute; criptografia
            e seguran&ccedil;a de dados. Desde crian&ccedil;a, adorava jogar <em>video-games</em> e experimentar com programas no computador.
            Conforme cresceu, amadureceu junto seu interesse por m&aacute;quinas. Com 14 anos de idade, aprendeu bastante sobre p&oacute;rtas l&oacute;gicas
            e, para concluir tudo o que aprendeu, construiu um computador b&aacute;sico utilizando circuitos em Minecraft (Inclusive, um de seus mapas
            ganhou <a href="https://youtu.be/aj5dJMbIALc?t=12m55s">mais de 100k visualiza&ccedil;&otilde;es</a> no Youtube, ao ser jogado por RageGamingVideos). De l&aacute;, come&ccedil;ou a
            se interessar por programa&ccedil;&atilde;o, aprendendo inicialmente a linguagem <a href="https://www.lua.org/">lua</a>, depois indo para <a href="https://www.python.org/">Python</a>.
        </p>
        <p>&emsp;&emsp;&emsp;&emsp;
            Participou, em sua escola (<a href="http://www.gracinha.g12.br/#/">Escola Nossa Senhora das Gra&ccedil;as</a>), de v&aacute;rios cursos extracurriculares
            de teor cient&iacute;fico, como duas 'Semanas de Ci&ecirc;ncias, Tecnologia e Sociedade' (inclusive, fazendo a palestra "O que &eacute; um computador?"
            na segunda), tr&ecirc;s 'Desafios de Ci&ecirc;ncias e matem&aacute;tica', duas participa&ccedil;&otilde;es na Ol&iacute;mpiada Brasileira de Matem&aacute;tica,
            al&ecirc;m de ser um dos co-fundadores do 'Ci&ecirc;ncias Organizadas do Gracinha', um modelo de simula&ccedil;&atilde;o parecido com o F&oacute;rum FAAP,
            entretanto visando a discuss&atilde;o de &acirc;mbito cient&iacute;fico.
        </p>
        <p>&emsp;&emsp;&emsp;&emsp;
            Hoje, &eacute; capacitado em Python, C, C++, C#, HTML, CSS, Javascript; e tem no&ccedil;&otilde;es de R, lua e bash.
        </p>
        <h4></h4>
    </div>
</div>
</body>
</html>

app/views/raz/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- Metas -->
    <!-- Title & icon -->
    <link rel="icon" href="imgref/razIcon.png">
    <!--CSS stylesheets -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/raz.css">
    <link rel="stylesheet" href="css/animate.css">
    <!-- Github octicons -->
    <!-- Js scripts -->
     <script src="js/bootstrap.min.js"></script>
     <script src="js/npm.js"></script>
     <script src="js/razgriz.js"></script>
     <!-- Angular modules -->
     <script src="js/app.js"></script>
     <!-- Angular Controllers -->
     <script src="js/controllers/MainController.js"></script>
</head>
<body ng-app="RazgrizOne">

<header>
    <div class="container-fluid spaced text-center animated fadeInDown" id="header">
        <div class="w3-center w3-container" id="Title">
            <div class="w3-hide-small">
                <%= link_to image_tag('RazLogo.png'), index_path %>
            </div>
            <div class="w3-hide-medium w3-hide-large">
                <a href="#"><img src="imgref/RazLogo.png" alt="logo" style="width: 60%; height: 60%; margin-top: -140px; margin-bottom: -100px;"></a>
            </div>
        </div>
        <div>
            <em>Pedro Pereira, IME - USP</em>
        </div>
    </div>
    <ul class="w3-navbar w3-black w3-border w3-card-4 animated fadeInDown" style="border: 0px !important;" id="InitNavbar">
        <li><b><%= link_to 'Bio', bio_path, class: "w3-hover-red" %></b></li>
        <li><a class="w3-hover-red" href="links.html"><b>Links</b></a></li>
        <li><a class="w3-hover-red" href="posts.html"><b>Posts</b></a></li>
        <li><a class="w3-hover-red" href="projects.html"><b>Projects</b></a></li>
    </ul>
</header>
<br />
<div class="w3-row-padding" id="Start">
    <div class="col-sm-2 col-md-3 spacing animated fadeInUp">
        <div id="latest-news" class="w3-border" ng-controller="News">
            <div class="w3-card-4 w3-container" style="background-color: #af0202; color: #FFF">
                <h4 class="w3-center">Not&iacute;cias Relevantes <span class="octicon octicon-radio-tower"></span></h4>
                <p class="w3-center subtitle">&Uacute;ltimo update: {{ lastChange | date }}</p>
            </div>
            <ul class="w3-ul w3-hoverable w3-center">
                <div ng-repeat="news in lastNews">
                    <a ng-href="{{ news.link }}"><li class="w3-hover-pale-red w3-round-large">{{ news.title }}</li></a>
                </div>
            </ul>
        </div>
    </div>
    <br>
    <div class="w3-rest spacing w3-panel animated fadeInUp" id="main">
        <div ng-controller="PostList" style="background-color: #DDD; border-radius: 0px 0px 8px 8px !important;" class="w3-border">
            <div id="latestProjTitle" class="w3-red w3-text-black w3-card-4">
                <h2 class="w3-center">&Uacute;ltimos Posts <span class="mega-octicon octicon-rss"></span></h2>
            </div>
            <div class="w3-container w3-accordion" id="latestProj">
                <div ng-repeat="post in postTexts">
                    <button ng-attr-id="{{ 'post' + $index }}" ng-click="openSec($event)" class="w3-ripple w3-btn-block w3-center w3-black">
                        <b>{{ post.title }}</b>
                    </button>
                    <div class="w3-accordion-content w3-container">
                        <p style="pre-line" ng-bind-html="post.text"></p>
                        <div class="wrapper-center">
                            <a style="padding:0; border: none; background: none;" ng-href="https://linux.ime.usp.br/~razgrizone/posts.html#{{ post.postNo }}">
                                <!-- <span class="octicon octicon-plus"></span> -->
                                <h2 style="font-size: 30px; font-style: bold;">...</h2>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="wrapper-center" style="margin-bottom: 10px;">
                <a href="posts.html" class="w3-btn animated w3-white w3-ripple">See all</a>
            </div>
        </div>
    </div>
</div>

</body>
</html>

app/views/raz/links.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="imgref/razIcon.png">
    <!--CSS stylesheets -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/raz.css">
    <link rel="stylesheet" href="css/animate.css">
    <!-- Js scripts -->
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
     <script src="js/bootstrap.min.js"></script>
     <script src="js/npm.js"></script>
     <script src="js/razgriz.js"></script>
</head>
<body>
    <header>
        <div class="container-fluid spaced text-center animated fadeInDown" id="header">
            <div class="w3-center w3-container" id="Title">
                <div class="w3-hide-small">
                    <a href="index.html"><img src="imgref/RazLogo.png" alt="Logo" style="width: 35%; height: 35%; margin-top: -140px; margin-bottom: -100px;"></a>
                </div>
                <div class="w3-hide-medium w3-hide-large">
                    <a href="index.html"><img src="imgref/RazLogo.png" alt="logo" style="width: 60%; height: 60%; margin-top: -140px; margin-bottom: -100px;"></a>
                </div>
            </div>
            <div>
                <em>Pedro Pereira, IME - USP</em>
            </div>
        </div>
        <ul class="w3-navbar w3-black w3-border w3-card-4 animated fadeInDown" style="border: 0px !important;" id="InitNavbar">
            <li><a class="w3-hover-red" href="bio.html"><b>Bio</b></a></li>
            <li><a class="w3-red w3-hover-white" href="#"><b>Links</b></a></li>
            <li><a class="w3-hover-red" href="posts.html"><b>Posts</b></a></li>
            <li><a class="w3-hover-red" href="projects.html"><b>Projects</b></a></li>
        </ul>
    </header>
    <br />
    <div class="w3-half wrapper-center w3-container animated fadeInUp">
        <a href="https://github.com/pedro823">
        <div class="w3-card-4 w3-panel sparse"  style="background-color: #eeeeee;">
            <h2>Meu github!</h2>
            <img src="imgref/ghlogo.png" alt="Github!" style="width: 200px;">
        </div>
        </a>
        <a href="http://codeforces.com/profile/pedro823">
        <div class="w3-card-4 w3-panel sparse">
            <h2>Meu perfil do Codeforces!</h2>
            <img src="http://st.codeforces.com/s/30025/images/codeforces-logo.png">
        </div>
        </a>
    </div>
    <div class="w3-half wrapper-center w3-panel animated fadeInUp" style="margin-top: 16px;">
        <a href="https://devpost.com/pedro823">
            <div class="w3-card-4 w3-container sparse" style="background-color: #dbedff;">
                <h2>Meu devpost!</h2>
                <p>Eu uso ele para inscri&ccedil;&otilde;es em hackathons.</p>
                <img alt="Devpost" src="https://devpost-challengepost.netdna-ssl.com/assets/reimagine2/devpost-logo-646bdf6ac6663230947a952f8d354cad.svg" style="width: 200px;">
            </div>
        </a>
        <a href="http://steamcommunity.com/id/lookoutitscreepah">
            <div class="w3-card-4 w3-panel sparse" style="background-color: #ddd">
                <h2>Minha conta da Steam</h2>
                <img alt="Steam" src="imgref/steam.png">
            </div>
        </a>
    </div>
</body>
</html>

app/views/raz/posts.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="imgref/razIcon.png">
    <!--CSS stylesheets -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/raz.css">
    <link rel="stylesheet" href="css/animate.css">
    <!-- Js scripts -->
     <script src="js/bootstrap.min.js"></script>
     <script src="js/npm.js"></script>
     <script src="js/razgriz.js"></script>
     <!-- Posts module  -->
     <script src="js/app.js"></script>
     <!-- Posts controllers -->
     <script src="js/controllers/MainController.js"></script>
</head>
<body ng-app="RazgrizOne">
    <header>
        <div class="container-fluid spaced text-center animated fadeInDown" id="header">
            <div class="w3-center w3-container" id="Title">
                <div class="w3-hide-small">
                    <a href="index.html"><img src="imgref/RazLogo.png" alt="Logo" style="width: 35%; height: 35%; margin-top: -140px; margin-bottom: -100px;"></a>
                </div>
                <div class="w3-hide-medium w3-hide-large">
                    <a href="index.html"><img src="imgref/RazLogo.png" alt="logo" style="width: 60%; height: 60%; margin-top: -140px; margin-bottom: -100px;"></a>
                </div>
            </div>
            <div>
                <em>Pedro Pereira, IME - USP</em>
            </div>
        </div>
        <ul class="w3-navbar w3-black w3-border w3-card-4 animated fadeInDown" style="border: 0px !important;" id="InitNavbar">
            <li><a class="w3-hover-red" href="bio.html"><b>Bio</b></a></li>
            <li><a class="w3-hover-red" href="links.html"><b>Links</b></a></li>
            <li><a class="w3-red w3-hover-white" href=""><b>Posts</b></a></li>
            <li><a class="w3-hover-red" href="projects.html"><b>Projects</b></a></li>
        </ul>
    </header>
    <br><br>
    <div class="wrapper-center" ng-controller="PostList">
        <div class="w3-card-8 animated fadeInUp" style="margin-left: 18%; margin-right:18%; margin-bottom:40px;" ng-repeat="post in postTexts">
            <div ng-attr-id="{{ post.postNo }}" class="spaced w3-red">
                <h1>{{ post.title }}</h1>
                <p style="font-size: 13px;">{{ post.date | date }}</p>
            </div>
            <div class="expanded-segment-square" style="padding-top: 15px; padding-bottom: 5px; padding-left: 30px; padding-right: 30px;">
                <p class="blue-links" ng-bind-html="post.wholeText"></p>
                <p class="monospace" ng-bind-html="post.code"></p>
            </div>
        </div>
    </div>
</body>
</html>

app/views/raz/projects.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="imgref/razIcon.png">
    <!--CSS stylesheets -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/raz.css">
    <link rel="stylesheet" href="css/animate.css">
    <!-- Github octicons -->
    <!-- Js scripts -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/npm.js"></script>
    <script src="js/razgriz.js"></script>
    <!-- Angular modules -->
    <script src="js/app.js"></script>
    <!-- Angular Controllers -->
    <script src="js/controllers/MainController.js"></script>
</head>
<body ng-app="RazgrizOne">
    <header>
        <div class="container-fluid spaced text-center animated fadeInDown" id="header">
            <div class="w3-center w3-container" id="Title">
                <div class="w3-hide-small">
                    <a href="index.html"><img src="imgref/RazLogo.png" alt="Logo" style="width: 35%; height: 35%; margin-top: -140px; margin-bottom: -100px;"></a>
                </div>
                <div class="w3-hide-medium w3-hide-large">
                    <a href="index.html"><img src="imgref/RazLogo.png" alt="logo" style="width: 60%; height: 60%; margin-top: -140px; margin-bottom: -100px;"></a>
                </div>
            </div>
            <div>
                <em>Pedro Pereira, IME - USP</em>
            </div>
        </div>
        <ul class="w3-navbar w3-black w3-border w3-card-4 animated fadeInDown" style="border: 0px !important;" id="InitNavbar">
            <li><a class="w3-hover-red" href="bio.html"><b>Bio</b></a></li>
            <li><a class="w3-hover-red" href="links.html"><b>Links</b></a></li>
            <li><a class="w3-hover-red" href="posts.html"><b>Posts</b></a></li>
            <li><a class="w3-red w3-hover-white" href=""><b>Projects</b></a></li>
        </ul>
    </header>
    <br><br>
    <div class="wrapper-center" ng-controller="ProjectList">
        <div class="w3-card-8 animated fadeInUp" style="margin-left: 18%; margin-right:18%; margin-bottom:40px;" ng-repeat="project in projects">
            <div class="spaced w3-indigo">
                <h1>{{ project.title }}</h1>
                <p style="font-size: 13px;"><em>{{ project.date | date }} - <b>{{ project.type }}</b></em></p>
            </div>
            <div class="expanded-segment-square" style="padding-top: 20px; padding-bottom: 10px; padding-left: 40px; padding-right: 40px;">
                <img ng-src="postImgs/proj/{{ project.image }}" style="width: 700px;">
                <p class="image-subtitle" style="margin-top: 10px;"><em>{{ project.subtitle }}</em></p>
                <p ng-bind-html="project.description" class="project-description" style="font-size: 18px;"></p>
                <a ng-href="{{ project.link }}" class="w3-btn w3-red w3-hover-white"><span class="octicon octicon-search"></span><b> Link</b></a>
            </div>
        </div>
    </div>
</body>
</html>